name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run on every push to main branch
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 1. Generate Activity SVG
      - name: Generate Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          user: rosamalave
          template: classic
          base: header, activity
          commits_authoring: yes
          filename: activity.svg
          output_action: commit
      
      # 2. Generate Repository Stats SVG
      - name: Generate Repository Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          user: rosamalave
          template: classic
          base: header, repositories
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_featured: ""
          plugin_repositories_pinned: 0
          plugin_repositories_starred: no
          plugin_repositories_random: 0
          filename: repositories-stats.svg
          output_action: commit
      
      # 3. Generate Languages SVG
      - name: Generate Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          use_prebuilt_image: yes
          user: rosamalave
          template: classic
          base: header
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, bytes
          plugin_languages_sections: most-used
          filename: languages.svg
          output_action: commit
